import React from 'react'
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
  } from "@/components/ui/accordion"
  
const Accordtion = () => {
  return (
    <div id='faq' className='bg-gray border-solid-2px rounded-xl p-2'>
        <h1 className='text-[3rem] font-medium'>FAQ</h1>
      <Accordion type="single" collapsible>
  <AccordionItem value="item-1">
    <AccordionTrigger>Is there any Refund ?</AccordionTrigger>
    <AccordionContent>
      According to our policy there is no refund once you have completed payment
    </AccordionContent>
  </AccordionItem>
  <AccordionItem value="item-2">
    <AccordionTrigger>How many days credits are valid ?</AccordionTrigger>
    <AccordionContent>
      The credits are valid until you use it
    </AccordionContent>
  </AccordionItem>
  <AccordionItem value="item-3">
    <AccordionTrigger>How it is better ?</AccordionTrigger>
    <AccordionContent>
      This hooks are generated by model, which generates human-connectionable texts, which attracts audience
    </AccordionContent>
  </AccordionItem>
  <AccordionItem value="item-4">
    <AccordionTrigger>Can we get more credits ?</AccordionTrigger>
    <AccordionContent>
      Soon we will provide better paying options for more credits
    </AccordionContent>
  </AccordionItem>
</Accordion>

    </div>
  )
}

export default Accordtion
